# Task 1:

### P1.1 Write a function to compute 5/0 and use try/except to catch the exceptions

#### Method 1

In [8]:
def func_try_except():
    try:
        print(5/0)
    except ZeroDivisionError:
        print("We can not devide a number by 0")
func_try_except()



We can not devide a number by 0


#### By acceping number from user

In [8]:
def func_try_except_user(number):
    try:
        result=5/number
        print("Result: "+str(result))
    except ZeroDivisionError:
        print("We can not devide a number by 0")
    except:
        print("Please enter a numeric value")
        
while True:
    quite=""
    number= float(input("\nPlease Enter a numeric value: "))
    func_try_except_user(number)
    quit=input("\nPlease y/Y for continnue or press any other kay for quit: ") 
    if quit.upper()=="Y":
        continue
    else:
        break


Please Enter a numeric value: 2
Result: 2.5

Please y/Y for continnue or press any other kay for quit: y

Please Enter a numeric value: 0
We can not devide a number by 0

Please y/Y for continnue or press any other kay for quit: dsd


### P1.2 Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

#### Nested loop

In [1]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in subjects:
    for v in verbs:
        for o in objects:
            print(s+" "+v+" "+o)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


#### Using list comprehensions

In [2]:
list1 = ([s+" "+v+" "+o for s in subjects for v in verbs for o in objects])
str1 = "\n"
str1= str1.join(list1)
print(str1)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

### Write a function so that the columns of the output matrix are powers of the input vector.
##### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [9]:
def vander(increasing_1,N):
    import numpy as np
    a=np.array([2,3,7,9])
    ismat=0
    
    if increasing_1=="False":
        matrix=np.vander(a,N)
        print(matrix)
        ismat=1
    elif increasing_1=="True":
        matrix=np.vander(a,N,increasing=True)
        print(matrix)
        ismat=1
    else:
        print("Please enter a boolean number")
    return ismat

#### Calling vandert function

In [11]:
while True:
    quite=""
    increasing_1=input("Please Enter Boolean Value(True/False):")
    N=int(input("Please Enter an integer:"))
    ismat=vander(increasing_1,N)
    if ismat!=0:
        print("\nvander function executed successfully")
        quit=input("Please y/Y for continnue or press any other kay for quit: ")
    else:
        quit=input("Please y/Y for continnue or press any other kay for quit: ") 
    if quit.upper()=="Y":
        continue
    else:
        break

Please Enter Boolean Value(True/False):True
Please Enter an integer:4
[[  1   2   4   8]
 [  1   3   9  27]
 [  1   7  49 343]
 [  1   9  81 729]]

vander function executed successfully
Please y/Y for continnue or press any other kay for quit: y
Please Enter Boolean Value(True/False):False
Please Enter an integer:4
[[  8   4   2   1]
 [ 27   9   3   1]
 [343  49   7   1]
 [729  81   9   1]]

vander function executed successfully
Please y/Y for continnue or press any other kay for quit: fdsf
